# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('proposeur', models.CharField(max_length=500)),
                ('contact_mail', models.EmailField(max_length=254)),
                ('date_publication', models.DateField(verbose_name="Date de publication de l'annonce")),
                ('date_fin', models.DateField(verbose_name='Date de fin de visibilit\xe9')),
                ('validee', models.BooleanField()),
                ('type_proposeur', models.CharField(choices=[(0, 'Entreprise'), (1, 'Suite PSC de 2A'), (2, "Proprosition d'un TC")], max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('proposeur', models.CharField(max_length=500)),
                ('contact_mail', models.EmailField(max_length=254)),
                ('date_publication', models.DateField(verbose_name="Date de publication de l'annonce")),
                ('date_fin', models.DateField(verbose_name='Date de fin de visibilit\xe9')),
                ('validee', models.BooleanField()),
                ('annee', models.CharField(choices=[(0, 'Stage 2A'), (1, 'Stage 3A')], max_length=20)),
                ('lieu', models.CharField(max_length=300)),
                ('periode', models.CharField(max_length=400)),
                ('remunere', models.BooleanField()),
                ('remuneration_mensuel', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
