# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-24 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('proposeur', models.CharField(max_length=500)),
                ('contact_mail', models.EmailField(default='', max_length=254)),
                ('date_publication', models.DateField(verbose_name="Date de publication de l'annonce")),
                ('date_fin', models.DateField(verbose_name='Date de fin de visibilit\xe9')),
                ('validee', models.BooleanField()),
                ('type_prop', models.CharField(choices=[(0, 'PSC'), (1, 'Stage 2A'), (2, 'Stage 3A')], max_length=20)),
                ('lieu', models.CharField(blank=True, max_length=300)),
                ('periode', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='PSC',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
